services:
  mongo:
    container_name: mongo
    build: ./mongo/
    ports:
      - 27017:27017
    restart: on-failure
    volumes:
      - ~/temp:/data/db  
  graphql:
    container_name: graphql
    build: ./graphql/
    ports:
      - 4000:80
    environment:
      - MONGO_URL=mongodb://192.168.50.101:27017/
    restart: on-failure
    depends_on:
      - mongo
    links:
      - mongo  
  graphql-client:
    container_name: graphql-client
    build: ./client/
    restart: on-failure
    depends_on:
      - graphql
  ui:
    container_name: ui     
    build:
      context: ./ui/
      args:
        - GRAPHQL_URL=http://192.168.50.101:4000/
    ports:
      - 80:80
    restart: on-failure
    depends_on:
      - graphql
      - graphql-client
